export const LOADING_HARDWARE_OFFERS_MOUSE = 'LOADING_HARDWARE_OFFERS_MOUSE';
export const HARDWARE_OFFERS_MOUSE_SUCCESS = 'HARDWARE_OFFERS_MOUSE_SUCCESS';
export const HARDWARE_OFFERS_MOUSE_FAILURE = 'HARDWARE_OFFERS_MOUSE_FAILURE';