export const LOAD_FORM_DATA = 'LOAD_FORM_DATA';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';
export const USER_PASSWORD_UPDATE_SUCCESS = 'USER_PASSWORD_UPDATE_SUCCESS';
export const USER_PASSWORD_UPDATE_FAILURE = 'USER_PASSWORD_UPDATE_FAILURE';
export const USER_ROLE_UPDATE_SUCCESS = 'USER_ROLE_UPDATE_SUCCESS';
export const USER_ROLE_UPDATE_FAILURE = 'USER_ROLE_UPDATE_FAILURE';
export const DEVELOPER_UPDATE_SUCCESS = 'DEVELOPER_UPDATE_SUCCESS';
export const DEVELOPER_UPDATE_ERROR = 'DEVELOPER_UPDATE_ERROR';
export const GETTING_USER_TYPES = 'GETTING_USER_TYPES';
export const GET_USER_TYPES_SUCCESS = 'GET_USER_TYPES_SUCCESS';
export const GET_USER_TYPES_ERROR = 'GET_USER_TYPES_ERROR';
export const GET_USERS_FOR_SUPPORT_SUCCESS = 'GET_USERS_FOR_SUPPORT_SUCCESS';
export const GET_USERS_FOR_SUPPORT_ERROR = 'GET_USERS_FOR_SUPPORT_ERROR';
export const GET_USERS_FOR_MARKETING_SUCCESS = 'GET_USERS_FOR_MARKETING_SUCCESS';
export const GET_USERS_FOR_MARKETING_ERROR = 'GET_USERS_FOR_MARKETING_ERROR';
export const DELETING_USER = 'DELETING_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';
export const GETTING_USER_PRODUCTS = 'GETTING_USER_PRODUCTS';
export const GET_USER_PRODUCTS_SUCCESS = 'GET_USER_PRODUCTS_SUCCESS';
export const GET_USER_PRODUCTS_ERROR = 'GET_USER_PRODUCTS_ERROR';

export const GETTING_USER_DETAILS = 'GETTING_USER_DETAILS';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_ERROR = 'GET_USER_DETAILS_ERROR';

export const SHOW_PROFILE_MODAL = 'SHOW_PROFILE_MODAL';
export const HIDE_PROFILE_MODAL = 'HIDE_PROFILE_MODAL';
export const SET_USER_ROLE_ADMIN_SECTION = 'SET_USER_ROLE_ADMIN_SECTION';

export const RESET_USER_DETAILS_STATE = 'RESET_USER_DETAILS_STATE';

export const SAVE_NOTE_PRODUCT_REDUX = 'SAVE_NOTE_PRODUCT_REDUX';
export const UPDATE_PRODUCT_NOTE_REDUX = 'UPDATE_PRODUCT_NOTE_REDUX';
export const DELETE_PRODUCT_NOTE_REDUX = 'DELETE_PRODUCT_NOTE_REDUX';